"""
git_ops.py
─────────────────────────────────────────────────────────────────────────────
Git automation layer.

Responsibilities:
  1. Commit all updated state JSON files back to the repository so the next
     GitHub Actions run picks up exactly where this one left off.
  2. Trigger the next workflow run via the GitHub Repository Dispatch API
     before the current run hits the 6-hour GitHub Actions timeout.
  3. Upload build artifacts to GitHub Releases (if available).
─────────────────────────────────────────────────────────────────────────────
"""

from __future__ import annotations

import logging
import os
import subprocess
import time
from pathlib import Path

import requests

logger = logging.getLogger("git_ops")

GITHUB_TOKEN: str = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO: str = os.getenv("GITHUB_REPOSITORY", "")   # "owner/repo"
GITHUB_BRANCH: str = os.getenv("GITHUB_REF_NAME", "main")
STATE_DIR: str = os.getenv("STATE_DIR", "state")


# ── Git commit ────────────────────────────────────────────────────────────────

def _run(cmd: list[str], cwd: str | None = None) -> tuple[int, str]:
    """Run a shell command, return (returncode, combined_output)."""
    result = subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
    )
    output = result.stdout + result.stderr
    if result.returncode != 0:
        logger.debug("CMD FAIL [%d]: %s\n%s", result.returncode, " ".join(cmd), output[:500])
    return result.returncode, output


def commit_state(
    message: str = "chore: persist engine state",
    paths: list[str] | None = None,
) -> bool:
    """
    Stage state JSON files and push a commit to the current branch.
    Returns True on success.
    """
    # Configure git identity (required in CI)
    _run(["git", "config", "user.email", "factory@ai-engine.bot"])
    _run(["git", "config", "user.name", "AI Software Factory"])

    # Stage state directory (and any other specified paths)
    stage_paths = [STATE_DIR] + (paths or [])
    for p in stage_paths:
        _run(["git", "add", p])

    # Check if anything changed
    rc, status = _run(["git", "status", "--porcelain"])
    if not status.strip():
        logger.info("[Git] Nothing to commit.")
        return True

    rc, out = _run(["git", "commit", "-m", message])
    if rc != 0:
        logger.error("[Git] Commit failed: %s", out[:400])
        return False

    rc, out = _run(["git", "push", "origin", GITHUB_BRANCH])
    if rc != 0:
        logger.error("[Git] Push failed: %s", out[:400])
        return False

    logger.info("[Git] ✓ State committed and pushed.")
    return True


# ── Repository Dispatch (self-trigger) ───────────────────────────────────────

def trigger_next_run(
    event_type: str = "engine_loop",
    client_payload: dict | None = None,
) -> bool:
    """
    Trigger the next GitHub Actions workflow run via Repository Dispatch.
    This is how the engine keeps itself alive across the 6-hour limit.
    Requires GITHUB_TOKEN with `repo` scope.
    """
    if not GITHUB_TOKEN or not GITHUB_REPO:
        logger.warning(
            "[Git] Cannot trigger next run – GITHUB_TOKEN or GITHUB_REPOSITORY not set."
        )
        return False

    url = f"https://api.github.com/repos/{GITHUB_REPO}/dispatches"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    payload = {
        "event_type": event_type,
        "client_payload": client_payload or {},
    }

    try:
        resp = requests.post(url, json=payload, headers=headers, timeout=30)
        if resp.status_code == 204:
            logger.info("[Git] ✓ Next run triggered via repository_dispatch.")
            return True
        else:
            logger.error(
                "[Git] Dispatch failed: HTTP %d – %s",
                resp.status_code,
                resp.text[:300],
            )
            return False
    except Exception as exc:
        logger.error("[Git] Dispatch error: %s", exc)
        return False


# ── GitHub Release upload ─────────────────────────────────────────────────────

def upload_release_asset(
    tag_name: str,
    asset_path: Path,
    release_name: str | None = None,
    release_body: str = "Auto-generated by AI Software Factory.",
) -> str | None:
    """
    Create (or reuse) a GitHub Release with the given tag, then upload
    the build artifact. Returns the download URL or None on failure.
    """
    if not GITHUB_TOKEN or not GITHUB_REPO:
        logger.warning("[Git] Cannot upload release – credentials not set.")
        return None

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    # 1. Create release
    create_url = f"https://api.github.com/repos/{GITHUB_REPO}/releases"
    create_payload = {
        "tag_name": tag_name,
        "name": release_name or tag_name,
        "body": release_body,
        "draft": False,
        "prerelease": False,
    }
    try:
        resp = requests.post(create_url, json=create_payload, headers=headers, timeout=30)
        if resp.status_code in (201, 422):   # 422 = tag already exists
            if resp.status_code == 422:
                # Fetch existing release
                get_resp = requests.get(
                    f"https://api.github.com/repos/{GITHUB_REPO}/releases/tags/{tag_name}",
                    headers=headers,
                    timeout=30,
                )
                release_data = get_resp.json()
            else:
                release_data = resp.json()
        else:
            logger.error("[Git] Release create failed: %d %s", resp.status_code, resp.text[:200])
            return None

        upload_url = release_data["upload_url"].replace("{?name,label}", "")
        release_html = release_data.get("html_url", "")

        # 2. Upload asset
        asset_name = asset_path.name
        upload_headers = {
            **headers,
            "Content-Type": "application/octet-stream",
        }
        with asset_path.open("rb") as fh:
            up_resp = requests.post(
                upload_url,
                headers=upload_headers,
                params={"name": asset_name},
                data=fh,
                timeout=120,
            )
        if up_resp.status_code == 201:
            download_url = up_resp.json().get("browser_download_url", release_html)
            logger.info("[Git] ✓ Asset uploaded: %s", download_url)
            return download_url
        else:
            logger.error("[Git] Asset upload failed: %d %s", up_resp.status_code, up_resp.text[:200])
            return release_html

    except Exception as exc:
        logger.error("[Git] Release upload error: %s", exc)
        return None
